/* eslint-disable key-spacing */

export default {
  resize: 'resize',
  webglcontextlost: 'webglcontextlost',
  webglcontextrestored: 'webglcontextrestored',
  remove: 'remove',
  movestart: 'movestart',
  load: 'load',
  contextmenu: 'contextmenu',
  dblclick: 'dblclick',
  click: 'click',
  touchcancel: 'touchcancel',
  touchmove: 'touchmove',
  touchend: 'touchend',
  touchstart: 'touchstart',
  dataloading: 'dataloading',
  mousemove: 'mousemove',
  mouseup: 'mouseup',
  mousedown: 'mousedown',
  sourcedataloading: 'sourcedataloading',
  error: 'error',
  data: 'data',
  styledata: 'styledata',
  sourcedata: 'sourcedata',
  mouseout: 'mouseout',
  styledataloading: 'styledataloading',
  moveend: 'moveend',
  move: 'move',
  render: 'render',
  zoom: 'zoom',
  zoomstart: 'zoomstart',
  zoomend: 'zoomend',
  boxzoomstart: 'boxzoomstart',
  boxzoomcancel: 'boxzoomcancel',
  boxzoomend: 'boxzoomend',
  rotate: 'rotate',
  rotatestart: 'rotatestart',
  rotateend: 'rotateend',
  dragend: 'dragend',
  drag: 'drag',
  dragstart: 'dragstart',
  pitch: 'pitch'
};
